server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ec2-13-209-72-91.ap-northeast-2.compute.amazonaws.com:3306/bebefriends?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: test1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 운영 환경에서는 데이터 손상 방지를 위해 validate 추천
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: false
