name: CI/CD Pipeline (without Docker)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: ./gradlew clean bootJar --no-daemon

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: .

      # scp로 서버에 빌드 파일 복사
      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: '*.jar'
          target: ${{ secrets.SERVER_DEPLOY_PATH }}

      # 서버에서 서비스 재시작
      - name: Restart service on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SERVER_DEPLOY_PATH }}
            PID=$(pgrep -f 'java')
            if [ -n "$PID" ]; then
              echo "Stopping process $PID"
              kill $PID
              sleep 10
            fi
#            nohup java -jar *.jar --spring.profiles.active=prod > app.log 2>&1 &
            nohup java -jar bebefriends-0.0.1-SNAPSHOT.jar --firebase.config-path=/home/ubuntu/bebe-friends3-firebase-adminsdk.json > app.log 2>&1 &

